# Generated by Django 3.1.6 on 2021-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('rfid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'username',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zaishitu',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('zaishitu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zaishitu',
                'managed': False,
            },
        ),
    ]
