# Generated by Django 3.1.6 on 2021-02-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('zaishitu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'html_output',
                'managed': False,
            },
        ),
    ]
